name = "gokulab-plataforma-de-evaluacion"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "frontend/dist"

[alias]
"net" = "cf-mongodb-polyfills/net"
"dns" = "cf-mongodb-polyfills/dns"
"tls" = "cf-mongodb-polyfills/tls"