name = "gokulab-platform"
main = "functions/_middleware.js"
compatibility_date = "2024-12-18"

[vars]
MONGODB_URI = "mongodb+srv://usuario:password@cluster.mongodb.net/"

[[kv_namespaces]]
binding = "GOKULAB_KV"
id = "tu-kv-id-aqui"