export const preguntasTest1 = [
  "Los libros son muy importantes para mí",
  "Fácilmente puedo memorizar números en mi cabeza",
  "Seguido visualizo imágenes cuando cierro mis ojos",
  "Práctico por lo menos un deporte o actividad física regularmente",
  "Tengo una voz agradable al cantar",
  "Soy el tipo de persona a la que la gente busca para pedirle consejos",
  "Paso tiempo meditando, reflexionando, o pensando en cuestiones importantes",
  "Oigo palabras en mi cabeza antes de leer, hablar o escribir",
  "Las matemáticas y/o las ciencias fueron mis materias favoritas",
  "Frecuentemente uso una cámara o grabadora para captar lo que veo",
  "Me cuesta trabajo permanecer sentado durante largos períodos",
  "Me doy cuenta cuando una nota está fuera de tono",
  "Cuando tengo un problema, busco a otra persona para que me ayude",
  "Tengo opiniones que me separan de la mayoría de la gente",
  "Aprendo más de escuchar la radio o música que de ver una película",
  "Me gusta resolver juegos y acertijos que requieren pensamiento lógico",
  "Me gusta hacer rompecabezas, laberintos, acertijos visuales",
  "Me gusta trabajar con las manos en actividades concretas",
  "Frecuentemente escucho la radio, discos, etc.",
  "Tengo por lo menos 3 mejores amigos",
  "Tengo un hobby especial que mantengo para mí mismo",
  "Tengo aptitudes para juegos de palabras como Scrabble, anagramas",
  "Me gusta armar experimentos de '¿Qué pasaría si...?'",
  "Tengo sueños muy claros durante las noches",
  "Las mejores ideas se me ocurren cuando hago actividad física",
  "Toco un instrumento musical",
  "Me gustan los pasatiempos sociales más que los juegos individuales",
  "Tengo metas importantes en mi vida sobre las cuales pienso regularmente",
  "Me gusta entretenerme con trabalenguas, versos, chistes",
  "Mi mente busca patrones, regularidades o secuencias lógicas",
  "Generalmente me oriento en territorio desconocido",
  "Frecuentemente utilizo ademanes con las manos al platicar",
  "Mi vida sería más pobre si no hubiera música en ella",
  "Disfruto de los retos de enseñar a otras personas lo que sé hacer",
  "Tengo una visión realista de mis fuerzas y debilidades",
  "Las personas me piden que les explique el significado de palabras",
  "Me interesan los nuevos desarrollos de la ciencia",
  "Me gusta dibujar o garabatear",
  "Necesito tocar los objetos para entender más de ellos",
  "Fácilmente puedo llevar el compás de una selección musical",
  "Me considero un líder (u otras personas me lo han dicho)",
  "Preferiría pasar un fin de semana solo en una cabaña en el bosque",
  "El inglés y la historia fueron más fáciles para mí que las matemáticas",
  "Creo que casi todo tiene una explicación racional",
  "Me fue más fácil la geometría que el álgebra en la escuela",
  "Disfruto de las actividades atrevidas como la montaña rusa",
  "Sé la música de muchas piezas musicales y canciones",
  "Me siento a gusto en medio de un tumulto (conciertos, etc.)",
  "Me considero de ideas fijas e independientes",
  "Recientemente escribí algo de lo que estoy muy orgulloso(a)",
  "Me siento más a gusto cuando algo ha sido medido o cuantificado",
  "Prefiero leer material con muchas ilustraciones",
  "Me describiría a mí mismo como bien coordinado",
  "Si escucho una pieza musical la puedo cantar bastante bien",
  "Me gusta involucrarme en actividades sociales",
  "Llevo un diario o agenda para llevar la cuenta de mi vida personal"
];

export const tiposInteligencia = [
  'LINGÜÍSTICA', 'LÓGICA', 'ESPACIAL', 'KINESTÉSICA', 
  'MUSICAL', 'INTERPERSONAL', 'INTRAPERSONAL'
];

export const matrizTest1 = [
  [1, 2, 3, 4, 5, 6, 7],
  [8, 9, 10, 11, 12, 13, 14],
  [15, 16, 17, 18, 19, 20, 21],
  [22, 23, 24, 25, 26, 27, 28],
  [29, 30, 31, 32, 33, 34, 35],
  [36, 37, 38, 39, 40, 41, 42],
  [43, 44, 45, 46, 47, 48, 49],
  [50, 51, 52, 53, 54, 55, 56]
];

export const atributosEmprendedores = [
  { id: 1, nombre: "Iniciativa", descripcion: "Capacidad para implementar nuevos servicios y estrategias sin esperar instrucciones", icono: "💡" },
  { id: 2, nombre: "Disciplina", descripcion: "Constancia en horarios, mantenimiento y cumplimiento de compromisos", icono: "⏰" },
  { id: 3, nombre: "Claridad de metas", descripcion: "Objetivos claros de crecimiento y posicionamiento en el mercado", icono: "🎯" },
  { id: 4, nombre: "Orden personal y operativo", descripcion: "Organización del espacio de trabajo y gestión eficiente de recursos", icono: "📋" },
  { id: 5, nombre: "Persistencia", descripcion: "Capacidad para mantener el negocio funcionando durante desafíos", icono: "💪" },
  { id: 6, nombre: "Toma de decisiones", descripcion: "Habilidad para elegir estrategias que beneficien el negocio", icono: "⚖️" },
  { id: 7, nombre: "Enfoque comercial", descripcion: "Orientación hacia la venta y fidelización de clientes", icono: "💰" },
  { id: 8, nombre: "Seguimiento a clientes", descripcion: "Atención post-servicio y construcción de relaciones duraderas", icono: "👥" },
  { id: 9, nombre: "Apertura al aprendizaje", descripcion: "Disposición para capacitarse en nuevas técnicas y tendencias", icono: "📚" },
  { id: 10, nombre: "Capacidad para resolver problemas", descripcion: "Habilidad para solucionar inconvenientes con clientes y proveedores", icono: "🔧" }
];